---

- name: Install Git 
  yum:
    name: git
    state: present
  become: true
- name: Make a directory for the source
  file:
    path: ./src
    state: directory
- name: Get the latest source code from github
  git:
    repo: "https://{{ github_username | urlencode }}:{{ github_password | urlencode }}@github.com/355gts/CovidCore.git"
    dest: ./src
- name: Make a directory for the config 
  file:
    path: ./config
    state: directory
- name: Get the config files
  find:
    paths: ./src/
    patterns: "appsettings.Template.json"
    use_regex: yes
    recurse: yes
  register: config_files
- debug:
    msg: "{{ item.path | regex_replace('^.*\\/(Covid.*)\\/appsettings\\.Template\\.json', '\\1.json') }}"
  with_items:
    - "{{ config_files.files }}"
- name: Template the Appsettings files
  template:
    src: "./{{ item.path }}"
    dest: "./config/{{ item.path | regex_replace('^.*\\/(Covid.*)\\/appsettings\\.Template\\.json', '\\1.json') }}"
  with_items:
    - "{{ config_files.files }}"
- name: Get a list of settings files to push into Openshift
  find: 
    paths: ./config/
  register: appsettings_files
- debug:
    msg: "{{ appsettings_files }}"
- name: Apply the ConfigMaps
  include: config_map.yaml config_file_path={{ item.path }}    
  with_items:
    - "{{ appsettings_files.files }}"        

